### ISSUE TITLE
Menu Hangs

### ISSUE THREAD

**Issue by W54J04S07T** [MatMoul/archdi-pkg#4]
There seems to be a "wait for" state
of some sort enabled  when one selects
a menu item.

Can this be reduced or eliminated?

**Comment by MatMoul** [comment]
It is because of the quality of sourceforge ...
I keep this method for a reason.
Unlike github, I can see the download statistics of each file.
But in the near future, I would provide a single compressed file that will avoid this problem.

I tag this issue to question, but i'll tag to ehancement later

**Comment by MatMoul** [comment]
Now archdi download only one compressed file and you don't need to wait...
